### ISSUE TITLE
JES 5.02 may not be working on MacOS Mojave (10.14)?

### ISSUE THREAD

**Issue by hcientist** [gatech-csl/jes#119]
It is maybe related to the following

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/tgm/Downloads/jes-5.020-macosx/JES.app/Contents/Resources/Java/dependencies/jython/Lib/runpy.py", line 94, in run_module
    return _run_module_code(code, init_globals, run_name,
  File "/Users/tgm/Downloads/jes-5.020-macosx/JES.app/Contents/Resources/Java/dependencies/jython/Lib/runpy.py", line 51, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/tgm/Downloads/jes-5.020-macosx/JES.app/Contents/Resources/Java/dependencies/jython/Lib/runpy.py", line 32, in _run_code
    exec code in run_globals
  File "/Users/tgm/Downloads/jes-5.020-macosx/JES.app/Contents/Resources/Java/jes/python/jes/__main__.py", line 14, in <module>
    setDockIcon()
  File "/Users/tgm/Downloads/jes-5.020-macosx/JES.app/Contents/Resources/Java/jes/python/jes/platform/macosx/__init__.py", line 59, in setDockIcon
    app.setDockIconImage(None)
	at com.apple.eawt._AppDockIconHandler.setDockIconImage(_AppDockIconHandler.java:77)
	at com.apple.eawt.Application.setDockIconImage(Application.java:346)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
```

I edited `jes-5.020-macosx/JES.app/Contents/Resources/Java/jes/python/jes/__main__.py` to remove the offending call and it seems to run well! (I am using [jenv](http://www.jenv.be/) to manage multiple java versions and have set `$JES_JAVA_HOME="$HOME/.jenv/versions/1.8.0.181"

**Comment by hcientist** [comment]
@mjguzdial for me this version does not work. Though perhaps some others can solve it by installing the default 1.6 jdk if they have it somewhere.

in the `jes-launcher.sh` this version insists java be located at `JAVA="/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/bin/java"`, but I started using jenv (see above) and so for me it's more convenient to use the `JES_JAVA_HOME` env var to specify my java. I couldn't readily find jdk 1.6 for Mac, so I am using 1.8. I don't knwo if it's related to this difference, but I then get the error in https://github.com/gatech-csl/jes/issues/119#issue-365702208 and that solution I mentioned applies here again.

**Comment by mjguzdial** [comment]
Try getting Java 6 here: https://support.apple.com/kb/dl1572?locale=en_US


- Mark

________________________________

**Comment by jlmayfield** [comment]
This is maybe off issue, but the special version for the MAC won't download. It either keeps restarting or stalls and times out.  The retina aware download keeps getting flagged as malware.  I have a few students use MAC and I'm not sure where to go from here if they can't get one of the workaround versions of JES to download.

**Comment by mjguzdial** [comment]
How about this version?

https://computinged.wordpress.com/2019/07/22/beta-release-of-new-jes-jython-environment-for-students-now-available-media-computation-for-python-ide/


------
Mark Guzdial, mjguz@umich.edu

   - Professor of Electrical Engineering and Computer Science, and
   Engineering Education Research, College of Engineering and
   Professor of Information, School of Information (courtesy)
   - Blog: http://computinged.wordpress.com

**Comment by jlmayfield** [comment]
I found that link in another issue and that seems to do the trick. I'll report back if we have further problems.

**Comment by mjguzdial** [comment]
Please try the beta version here: https://computinged.wordpress.com/2019/07/22/beta-release-of-new-jes-jython-environment-for-students-now-available-media-computation-for-python-ide/ <https://computinged.wordpress.com/2019/07/22/beta-release-of-new-jes-jython-environment-for-students-now-available-media-computation-for-python-ide/>

I’m running Mojave and it’s working for me.

 - Mark

**Comment by mjguzdial** [comment]
Yeah, I have to figure out if it's worth dealing with that. Thanks!
 - Mark
------
Mark Guzdial, mjguz@umich.edu

   - Professor of Electrical Engineering and Computer Science, and
   Engineering Education Research, College of Engineering and
   Professor of Information, School of Information (courtesy)
   - Blog: http://computinged.wordpress.com
